version: "3.9"

services:
  django:
    build:
      context: ./backend/django
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db_django

  db_django:
    image: postgres:13-alpine
    volumes:
      - dev-djangodb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  flask:
    build:
      context: ./backend/flask
      dockerfile: Dockerfile
    depends_on:
      - db_flask
    environment:
      FLASK_APP: /usr/local/bin/app.py
      POSTGRES_DB: employees_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5500:5500"

  db_flask:
    image: postgres:latest
    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./backend/flask/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dev-flaskdb-data:/var/lib/postgresql/data

  react-app:
    build:
      context: ./yaml-editor
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"

volumes:
  dev-flaskdb-data:
  dev-djangodb-data:
